# Generated by Django 3.0.2 on 2020-02-13 12:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('calling_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '987xxxxxxx'", regex='^\\+?1?\\d{10,11}$')])),
                ('contact_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '987xxxxxxx'", regex='^\\+?1?\\d{10,11}$')])),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('pin', models.IntegerField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
