# Generated by Django 3.0.2 on 2020-02-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='edit_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='edited_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
